99cats/config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  root to: redirect("/cats")
end

99cats/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  has_many :cats
  has_many :cat_rental_requests

  validates :user_name, :password_digest, presence: true
  validates :user_name, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return user if user && user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

99cats/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_if_logged_in
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!
      redirect_to cats_url
    else
      flash[:errors] = ["User wasn't created!"]
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

99cats/app/views/users/create.html.erb
<h1> TEST!</h1>

99cats/app/views/users/new.html.erb
<h1> Create a New User!</h1>
<% if flash[:errors] %>
 
  <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    </ul>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="POST">

  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <p>
    <label for="user_name">Name:</label>
    <input type="text" name="user[user_name]" id="user_name">
  </p>


  <p>
    <label for="password">Password:</label>
    <input type="text" name="user[password]" id="password">
  </p>

  <p>
    <input type="submit" value="Create User">
  </p>
</form>